# NUMPY BASICS

# Intro to NumPy

NumPy is the fundamental package for scientific computing in Python. NumPy is used in many other packages in python even though you may not see it explicitly running in your code.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.




### install the numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
import numpy
a = numpy.arange(10)
print (a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [4]:
print (a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype.name)
print(type(a[0]))
print(a.data)
print(type(a))


1
10
4
int32
<class 'numpy.int32'>
<class 'numpy.ndarray'>


### Makes the processing faster


In [5]:
a =[1,2,3]
b =[4,5,6]
for i in range(len(a)):
    print(a[i]*b[i])

4
10
18


In [6]:
import numpy as np
a = np.arange(1,4)
print(a)
b =  np.arange(4,7)
print(b)
print(a*b)

[1 2 3]
[4 5 6]
[ 4 10 18]


 #### Import the numpy package

In [7]:
import numpy as np

In [8]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.arange(10).reshape(2,5).reshape(5,2)
print (a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
a = np.arange(10).reshape(5,2)
print (a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
print (a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype.name)
print(type(a))

2
10
4
int32
<class 'numpy.ndarray'>


In [12]:
import numpy as np

In [13]:
a = np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
a = np.arange(10).reshape(2,5)
print (a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
a = np.arange(12).reshape(2,3,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [16]:
a = np.arange(27).reshape(3,3,3)
print (a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
a = np.arange(0,27,5).reshape(2,3)
print (a)

[[ 0  5 10]
 [15 20 25]]


In [18]:
a = np.arange(64).reshape(2,2,4,4)
print (a)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]
   [12 13 14 15]]

  [[16 17 18 19]
   [20 21 22 23]
   [24 25 26 27]
   [28 29 30 31]]]


 [[[32 33 34 35]
   [36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]

  [[48 49 50 51]
   [52 53 54 55]
   [56 57 58 59]
   [60 61 62 63]]]]


In [19]:
a = np.arange(24).reshape(2,6,2).reshape(2,2,2,3)
print(a)
print(a.ndim)

[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]
4


In [20]:
a = np.arange(10).reshape(5,2)
print (a)
print("################################")
e =a.reshape(2,5)
print(e)
print("################################")
b = np.arange(10).reshape(5,2)
print(b)
print("################################")
c = b.reshape(10,1)
print(c)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
################################
[[0 1 2 3 4]
 [5 6 7 8 9]]
################################
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
################################
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [21]:
print (a.ndim)
print(a.size)
print(a.itemsize)
print(a.dtype.name)
print(type(a))

2
10
4
int32
<class 'numpy.ndarray'>


#### using list to generate numpy array

In [30]:
b=np.array([2,3,4])
print(b)
print(b.dtype)

[2 3 4]
int32


In [ ]:
d = b.reshape(3,1)
print(d)

In [3]:
import numpy as np
c=np.array([[1,2],[3,4]])
print (c)
print("##############")
d=np.array([[1,2],[3,4]]).reshape(1,4)

print(d)
print("##############")

e = np.array([3,6,9,12,14,16,18,19]).reshape(2,2,2)
print(e)
print("##############")


[[1 2]
 [3 4]]
##############
[[1 2 3 4]]
##############
[[[ 3  6]
  [ 9 12]]

 [[14 16]
  [18 19]]]
##############


In [32]:
c=np.array([[1,2],[3,4.0]],dtype='int')
print (c)
print(c.dtype.name)

[[1 2]
 [3 4]]
int32


In [4]:
c=np.array([[1,2],[3,4]],dtype='complex')
print (c)
print(c.dtype.name)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128


In [5]:
c=np.array([[1,2],[3,4+5j]],dtype='int')
print (c)

TypeError: can't convert complex to int

In [6]:
a =3.90
b = int(a)
b

3

In [7]:
t = np.arange(4).reshape(2,2)
print(t)

[[0 1]
 [2 3]]


In [ ]:
t = np.arange(8).reshape(4,2)
print(t)

In [9]:
t = np.arange(8).reshape(2,2,2)
print(t)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [10]:
t = np.arange(16).reshape(2,2,2,2)
print(t)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [ ]:
print (t.ndim)
print(t.size)
print(t.itemsize)
print(t.dtype.name)

print(type(t))

In [12]:
a = np.arange(10,16)
print(a)
#start, end and step
b = np.arange(10,16,2)
print(b)
b = np.arange(16)
print(b)

[10 11 12 13 14 15]
[10 12 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [14]:
a = np.arange(10,16)
print(a)
#start, end and step
b = np.arange(22,116,-2)
print(b)
b = np.arange(22,16,-2)
print(b)

[10 11 12 13 14 15]
[]
[22 20 18]


### Generate Zeros

In [15]:
d=np.zeros([3,10])
print (d)
print(d.dtype.name)
d=np.zeros([2,3,3,4,5,1])
print (d.ndim, d)
print(d.dtype.name)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
float64
6 [[[[[[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]]


   [[[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]]


   [[[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]]]



  [[[[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]

    [[0.]
     [0.]
     [0.]
     [0.]
     [0.]]]


   [[[0.]
     [0.]
     [0.]
     [0.]
     [0.

In [16]:
e=np.empty([2,10])
print (e)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.24610723e-306
  8.34447260e-308 1.29062229e-306 7.56595733e-307 1.11256817e-306
  1.06811422e-306 1.42417221e-306]
 [1.11260619e-306 8.90094053e-307 1.86919378e-306 1.06809792e-306
  1.37962456e-306 1.69111861e-306 1.78020169e-306 1.37961777e-306
  7.56599807e-307 2.56761491e-312]]


In [ ]:
##Range Functionalities

In [49]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b=np.arange(10,30,5).reshape(2,2)
print (b)

In [ ]:
b=np.arange(10,36,5).reshape(3,2)#start, end, step
print (b)

In [52]:
c= np.linspace(10,60,20).reshape(2,10)#start, end, no of values required
print (c)

[[10.         12.63157895 15.26315789 17.89473684 20.52631579 23.15789474
  25.78947368 28.42105263 31.05263158 33.68421053]
 [36.31578947 38.94736842 41.57894737 44.21052632 46.84210526 49.47368421
  52.10526316 54.73684211 57.36842105 60.        ]]


In [20]:
c= np.linspace(0,50)#start, end, no of values required #default 50 values
print (c)
c= np.linspace(0,50,25).reshape(5,5)#start, end, no of values required
print (c)

[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]
[[ 0.          2.08333333  4.16666667  6.25        8.33333333]
 [10.41666667 12.5        14.58333333 16.66666667 18.75      ]
 [20.83333333 22.91666667 25.         27.08333333 29.16666667]
 [31.25       33.33333333 35.41666667 37.5        39.58333333]
 [41.66666667 43.75       45.83333333 47.91666667 50.        ]]


In [21]:
a = np.ones([2,3])
print (a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
c=np.array([[1,0,3],[4,0,6]])
print (c)
print(c.shape)

[[1 0 3]
 [4 0 6]]
(2, 3)


In [23]:
print(a*c)
print("###############################")
InverseC  = a/c
print("############# Inverse ##################")
print(InverseC)
print("###############################")
print(c*InverseC)

[[1. 0. 3.]
 [4. 0. 6.]]
###############################
############# Inverse ##################
[[1.                inf 0.33333333]
 [0.25              inf 0.16666667]]
###############################
[[ 1. nan  1.]
 [ 1. nan  1.]]


c:\python373\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
c:\python373\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in multiply
  import sys


In [24]:
b=np.random.random([3,3])
print (b)

[[0.16490465 0.59282208 0.76481425]
 [0.72555483 0.01353069 0.71010642]
 [0.65550879 0.42533179 0.45807002]]


In [29]:
b=np.random.random([2,3,4])
print (b)
#b=np.random.randint(2,3)
#print (b)

[[[0.78477484 0.50183796 0.67341183 0.12884779]
  [0.71231284 0.95353025 0.27303475 0.16733493]
  [0.45970684 0.17288398 0.6537165  0.08493566]]

 [[0.87987808 0.15707049 0.52650431 0.02842269]
  [0.85180217 0.51487395 0.47050464 0.46780852]
  [0.04437008 0.17378137 0.68558846 0.49800108]]]


In [30]:
c=np.random.random([2,3])
print (c)
print("#############################")
print ("sum of elements is ", c.sum())
print("#############################")
print ("least elements is ",c.min())
print("#############################")
print("largest of elements is ",c.max())
print("#############################")
print("round  of elements is ",c.round(3))

[[0.09826812 0.65587417 0.18006058]
 [0.82647838 0.49204229 0.41945813]]
#############################
sum of elements is  2.6721816672492746
#############################
least elements is  0.09826812201349189
#############################
largest of elements is  0.826478377682396
#############################
round  of elements is  [[0.098 0.656 0.18 ]
 [0.826 0.492 0.419]]


In [31]:
c=np.random.random([2,3])
print (c)
print("###########################")
print (c.sum())
print("###########################")
print (c.min())
print("###########################")
print(c.max())
print("###########################")
print(c.mean())
print("####### sum axis = 0####################")
print(c.sum(axis =0))
print("###########sum axis = 1################")
print(c.sum(axis =1))
print("###########cumulative sum axis = 0 ################")
print (c.cumsum(axis =0))
print("############cumulative sum axis = 1 ###############")
print (c.cumsum(axis =1))
print("###########################")

[[0.79497482 0.24879512 0.58423904]
 [0.40536462 0.81348276 0.56738383]]
###########################
3.41424018577252
###########################
0.24879511895115314
###########################
0.813482759899148
###########################
0.5690400309620867
####### sum axis = 0####################
[1.20033944 1.06227788 1.15162287]
###########sum axis = 1################
[1.62800898 1.7862312 ]
###########cumulative sum axis = 0 ################
[[0.79497482 0.24879512 0.58423904]
 [1.20033944 1.06227788 1.15162287]]
############cumulative sum axis = 1 ###############
[[0.79497482 1.04376994 1.62800898]
 [0.40536462 1.21884738 1.7862312 ]]
###########################


In [32]:
c = np.arange(12).reshape(2,2,3)
print(c)
print("#############################")
print (c.sum())
print("###########################")
print (c.min())
print("###########################")
print(c.max())
print("###########################")
print(c.mean())
print("####### sum axis = 0####################")
print(c.sum(axis =0))
print("###########sum axis = 1################")
print(c.sum(axis =1))
print("###########cumulative sum axis = 0 ################")
print (c.cumsum(axis =0))
print("############cumulative sum axis = 1 ###############")
print (c.cumsum(axis =1))
print("###########################")

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
#############################
66
###########################
0
###########################
11
###########################
5.5
####### sum axis = 0####################
[[ 6  8 10]
 [12 14 16]]
###########sum axis = 1################
[[ 3  5  7]
 [15 17 19]]
###########cumulative sum axis = 0 ################
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  8 10]
  [12 14 16]]]
############cumulative sum axis = 1 ###############
[[[ 0  1  2]
  [ 3  5  7]]

 [[ 6  7  8]
  [15 17 19]]]
###########################


In [33]:
a = np.arange(8).reshape(2,2,2)
print(a)
print("######################")
print(a.sum(axis=0))
print("#########")
print(a.sum(axis=1))
print("#########")
print(a.sum(axis=2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
######################
[[ 4  6]
 [ 8 10]]
#########
[[ 2  4]
 [10 12]]
#########
[[ 1  5]
 [ 9 13]]


#### Make an array from a list. 

This will create a numpy array with 3 elements. 

Each numpy array contains an attribute called `shape`. Shape is a tuple which tells you how many elements you have per axis. For example (5, 6, 8) means 5 elements per axis 0, 6 elements per axis 1 and 8 elements per axis 2. Usually you will have only one or two axes.

The shape for the array in this section is `(3, )`. The reason for this funny notation is python's type system where shape must be a tuple and this is a tuple with 1 element. Writing just 3 would mean a number, not a tuple.

To verify that try `np.array([1, 2, 3]).shape` 

In [ ]:
np.array([1, 2, 3]).shape

In [ ]:
np.array([[1, 2, 3]]).shape 

#### Make an array from a list of lists

The shape of this array is (2, 2) so this is a matrix.

In [ ]:
np.array([[1, 2], [3, 4]]).shape

#### Make an array using a function

The arrays made in previous sections were based on us supplying each value.

Very often we need large arrays and it is not possible to use our current approach and thus we need to use array creating functions. The most important functions are `zeros` and `ones`. They both take a parameter called shape which determines the shape of the output array.
* `zeros` makes an array which is all 0 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
* `ones`  makes an array which is all 1 [docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones((3, 2))

#### Make an array by starting at 0, incrementing by 2 and ending before 10

`arange` is the exact same thing as regular python `range` except giving back a numpy array.

This functions requires only a single argument which is the end point. The start point is assumed to be 0 and step is assumed to be 1.

In this variety when in takes three parameters, the first one is the start, second one is the end and the third one is the step.

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)

In [ ]:
np.arange(0, 10, 2)

#### Make an array of four evenly spaced numbers including both endpoints

In [ ]:
np.linspace(0, 1, 4)

#### Make an array of random numbers (using a normal distribution)

The random submodule of numpy contains a variety of functions for generating random numbers following a specified probability distributions or sampling from a finite set of choices. To learn more about it visit the [documentation](https://docs.scipy.org/doc/numpy/reference/routines.random.html). 

In [34]:
import numpy as np
mean = 10
stdev = 3
number_values = 100
resultant_array = np.random.normal(mean, stdev, number_values)
print(resultant_array )
print(resultant_array.mean())
print(resultant_array.std())
# for a poisson distribution a mean and standard deviation are equal 
resultant_array_1 = np.random.poisson(mean, number_values)
print(resultant_array_1)
print(resultant_array_1.mean())
print(resultant_array_1.std())

[ 8.21476521 11.32296147  8.10300909 12.3256369   9.63320122 12.52727032
 11.50974999 12.20866405  7.67800085  8.59652281  9.67973851 11.87047643
  9.79984747 13.93214417  6.0190913  13.60351582 13.78991854  8.19984865
  8.76789444  5.47628357  5.6862803  10.18214938 10.87707589  6.12496458
 10.49462956 13.00440776 15.02012377  9.30633474  8.73189246 10.45630549
  8.31370239 13.07442704  9.06873864 10.96721881 12.75994194  3.4570033
 12.50110198  2.63005752 13.74360612 10.04578693  8.99548413 10.64738136
 11.13210091  9.29157206 12.48698402  5.41670217 13.50880458 11.20109644
  9.10479429  5.99074935  9.48725337  8.68366051 14.15060421  8.13518433
 13.42531493 11.1112645  11.03013348 13.53451326 15.65754736  7.68246675
 10.14534449  7.95611004 10.30885555 14.9018087   9.17196027 13.07442166
 11.31643633 12.0484324   8.62664326  4.20260728 10.00917132 11.67908429
 15.84037909 15.30272398 11.96986026  7.66388806  6.22245201 11.68887388
 12.14948043  7.70772059 10.62965423  8.05457062  7.

## Indexing Arrays
#### Access elements of a 1-dimensional array.  Get the first and last element.

In python as is in many other programming languages all arrays start from 0 so the first element is at position 0.

To access the last element we can use -1 as the index. `x[-1]` is identical to `x[x.shape[0] - 1]` where `shape[0]` is the length of the array.

In [ ]:
x = np.arange(4)#.reshape(4)
print(x, x.shape)
print(x[0])
print(x[-1])

In [36]:
x = np.linspace(10,20,10).reshape(2,5)
print(x)
#Get first row
print("##########################")
print(x[0])
print("##########################")
print(x[0][1])
print("##########################")
print(x[0,-1])
print("##########################")
print(x[1,-2])

[[10.         11.11111111 12.22222222 13.33333333 14.44444444]
 [15.55555556 16.66666667 17.77777778 18.88888889 20.        ]]
##########################
[10.         11.11111111 12.22222222 13.33333333 14.44444444]
##########################
11.11111111111111
##########################
14.444444444444445
##########################
18.88888888888889


In [39]:

x = np.linspace(10,20,30).reshape(2,5,3)
x = x.round(0)
print(x)
print("##########################")
#Get first row
print(x[0])
print("##########################")
print(x[0][1])
print("##########################")
print(x[0][-1])
print("##########################")
print(x[0,4])
print("##########################")
print(x[0,2,1])

[[[10. 10. 11.]
  [11. 11. 12.]
  [12. 12. 13.]
  [13. 13. 14.]
  [14. 14. 15.]]

 [[15. 16. 16.]
  [16. 17. 17.]
  [17. 18. 18.]
  [18. 19. 19.]
  [19. 20. 20.]]]
##########################
[[10. 10. 11.]
 [11. 11. 12.]
 [12. 12. 13.]
 [13. 13. 14.]
 [14. 14. 15.]]
##########################
[11. 11. 12.]
##########################
[14. 14. 15.]
##########################
[14. 14. 15.]
##########################
12.0


#### Reshape an array

Remember that shape is the fundamenal property of each array and we can modify it as we desire and we often do so. To change the shape of an array we use the `reshape` method.

The code in this example creates an 1D-array of 6 elements using the `arange` functon.

We convert it to a 2D-array using the `reshape` method.

You see that the total amount of numbers did not change, only our view of them. 6 elements in a vector or 3 x 2 elements in a matrix.

It is very important that when using `reshape` to ensure that dimensions match or you will get an error. 6 = 3 x 2 is a match so this works but trying np.arange(6).reshape(4, 2) will give you an error. 

[docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

In [ ]:
x = np.arange(6).reshape(2, 3)
print(x)

#### Get the last row

When dealing with arrays which are of more than a single dimension we can use partial indexing specifications go slice the array the way we want. 

For example `print(x[-1])` will print the last **row**.

To get the last column take the transpose of the 2d-array and then use [-1]. 

For exampe `print(x.T[-1])` will give you the last columns. `x.T` is the transpose of `x`

In [ ]:
print(x[-1])

#### Get the last element of the last row

Here we are using full indexing to get a single **element**.

In [ ]:
print(x[-1, -1])

#### Get elements like a list

Using the notation `a:b` we can slice arrays as precisely as we want.

`a:b` means give me back all elements whose positions is in that set.

For example `y = [1, 3, 5, 7, 9]` and `y[0:2]` would give us the first two elements `[1, 3]`.

Negative indices mean from back so -3 means 3 positions starting from the last position.

Experiment with the values until you get the feel for it.

In [40]:
x = np.arange(10) 

print(x)
print(x[:3])
print(x[1:4])
print(x[-3:])
print(x[-5:-1:2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2 3]
[7 8 9]
[5 7]


In [41]:
x = np.arange(27).reshape(3,3,3) 
print("######################")
print(x)
print("######################")
print(x[2:3])
print("######################")
print(x[1:2])
print("######################")
print(x[-3:])


######################
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
######################
[[[18 19 20]
  [21 22 23]
  [24 25 26]]]
######################
[[[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
######################
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(x)
print("$$$$$$$$$$$$$$$$$$")
print(x[:])
print("$$$$$$$$$$$$$$$$$$")
print(x[:,::2])
print("$$$$$$$$$$$$$$$$$$")
print(x[:,::2,::2])
print("$$$$$$$$$$$$$$$$$$")

In [47]:

print("############################")
print(x[:,::2,::2]) # Get all the corner values in the matrices
print("############################")
print(x[::-1])
print("############two levels ################")
print(x[::-1,::-1])
print("############################")
print(x[::-1,::-1,::-1]) # Get all the corner values in the matrices
print("############################")
print(x[:,::-1,::-1]) # Get all the corner values in the matrices
print("############################")
print(x[:,::-2,::-2]) # Get all the corner values in the matrices

############################
[[[ 0  2]
  [ 6  8]]

 [[ 9 11]
  [15 17]]

 [[18 20]
  [24 26]]]
############################
[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
############two levels ################
[[[24 25 26]
  [21 22 23]
  [18 19 20]]

 [[15 16 17]
  [12 13 14]
  [ 9 10 11]]

 [[ 6  7  8]
  [ 3  4  5]
  [ 0  1  2]]]
############################
[[[26 25 24]
  [23 22 21]
  [20 19 18]]

 [[17 16 15]
  [14 13 12]
  [11 10  9]]

 [[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]]
############################
[[[ 8  7  6]
  [ 5  4  3]
  [ 2  1  0]]

 [[17 16 15]
  [14 13 12]
  [11 10  9]]

 [[26 25 24]
  [23 22 21]
  [20 19 18]]]
############################
[[[ 8  6]
  [ 2  0]]

 [[17 15]
  [11  9]]

 [[26 24]
  [20 18]]]


#### Get all elements in reverse order

The enhanced slicing syntax is `a:b:c` were `c` is the step. For example `0:10:2`.

If we omit `a` and `b` we always asume they are `a` = 0 and `b` = length of the list so we are only left with a step.

Thus `::2` means slicing from 0 to end with a step 2. `::3` mean slicing with a step 3.

Now what if we used negative steps. Using -1 as the step would reverse the logic and `a` becomes the end of the list and `b` becomes zero. So `::-1` will slice in reverse direction.

Finally there is also the slice form `::1` or written short `:` which means give me back all elements in order as they are present.

In [48]:
print(x[::-1])

[[[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]]


In [49]:
npreverse = np.arange(10).reshape(5,1,2)
print(npreverse)
print("##################### step =1")
print(npreverse[::1])
print("##################### step = 2")
print(npreverse[::2])
print("##################### step =-1")
print(npreverse[::-1])
print("##################### step =-2")
print(npreverse[::-2])

[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
##################### step =1
[[[0 1]]

 [[2 3]]

 [[4 5]]

 [[6 7]]

 [[8 9]]]
##################### step = 2
[[[0 1]]

 [[4 5]]

 [[8 9]]]
##################### step =-1
[[[8 9]]

 [[6 7]]

 [[4 5]]

 [[2 3]]

 [[0 1]]]
##################### step =-2
[[[8 9]]

 [[4 5]]

 [[0 1]]]


#### Get every second element or third element

In [50]:
print(x)
print("##########################")
print(x[::2])
print("##########################")
print(x[::3])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
##########################
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
##########################
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


#### Create a 5x5 matrix

In [51]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Get the first two columns and the first two rows

Until now you have learned how to slice on a 1D array but slices can be generalized to any dimensional arrays.

The trick is to create a slice for every dimensions. 

In this example we have a 2d-array so we create two slices, one for dimension 0 (rows) and one for dimension 1 (columns)


In [ ]:
print(x[:2, :2])

In [ ]:
print(x[-2:, -2:])

Get values in last two rows and last two columns for 0 to 25 shape - 5,5 

#### Get every second column of every second row

In [ ]:
print(x[::1, ::-3])

In [ ]:
print(x[::1, ::-3])

## Access parts of an array with index arrays

#### Generate six random integers between 0 and 9 inclusive

`randint` in `np.random` is a very useful function which generates uniformly distributed random integers from the range provided as its first two parameters (start and end of range respectively). It's third parameter tells the method how many numbers we need.

In [72]:
x = np.random.randint(0, 10, 6) 
print(x)
x = np.linspace(0, 10, 6)
print(x)

[8 9 3 6 3 0]
[ 0.  2.  4.  6.  8. 10.]


#### Get the first number and the last two numbers

Slices are inhetently linear and give us access to arrays in a linear fashion.

To access elements in any order we must use index arrays which are numpy arrays holding integer numbers which tell what elements to chose from the indexed array.

In [75]:
print(x)
indices = [0, -2, -1]
print(x[indices])
#print(x[0,-2,1])
print(x[[0, -2, -1]])
x[[0,-2,-1]]

[ 0.  2.  4.  6.  8. 10.]
[ 0.  8. 10.]
[ 0.  8. 10.]


array([ 0.,  8., 10.])

In [76]:
b = np.random.randint(0,20,20).reshape(4,5)
print(b)

[[19  5 11 10  2]
 [11  8 13 18 16]
 [16  2  3  4  5]
 [ 7  2  6  8 16]]


In [80]:
indices = [0, -1]
print(b[indices])
print("#########indexing over the axis#############")
print(b[0,-1])
print("######################")
indices_rows = [0, -1]
indices_cols = [4]
print(b[[indices_rows]])
print("###############################")
#print(b[[indices_rows][indices_cols]])
print("###############################")
print(b[[indices_rows, indices_cols]])



[[19  5 11 10  2]
 [ 7  2  6  8 16]]
#########indexing over the axis#############
2
######################
[[19  5 11 10  2]
 [ 7  2  6  8 16]]
###############################
###############################
[ 2 16]


c:\python373\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  
c:\python373\lib\site-packages\ipykernel_launcher.py:12: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  if sys.path[0] == '':


### Create two arrays

The array `x2` is created as `x1 * -1`. The multiplication operator here means multiply all elements of `x1` with -1 and give back that as result.

In [91]:
arrayLength = 5
x1 = np.arange(arrayLength)
x2 = np.arange(arrayLength) * -1

print(x1)
print(x2)

[0 1 2 3 4]
[ 0 -1 -2 -3 -4]


#### Create a random shuffled range of numbers

This and the following example shows how to shuffle an array in numpy.

Shuffling means reordering the items in an array and we can do that using random permutations of the array positions.

In [89]:
arrayLength = 5
indices = np.random.permutation(arrayLength)
print(indices)


[2 3 0 4 1]


In [92]:
x1[indices]

array([2, 3, 0, 4, 1])

In [93]:
x2[indices]

array([-2, -3,  0, -4, -1])

#### Use indices to re-order arrays

In [90]:
print(x1[indices])
print(x2[indices])

[2 3 0 4 1]
[-2 -3  0 -4 -1]


#### Create array of boolean values

The main novelty of this example is `print(x > 2)`.

`x > 2` generates an array of boolean values where each element is True or False.
Having True at position i of the output means that the conditions is satisfied for the element of `x` at position i.

For exampe if `x=[0,1,2,3,4]` then `x > 2` would be `[False, False, False, True, True]`.

As you see 0 > 2 = False, 1 > 2 = False, 2 > 2 = False, 3 > 2 = True and 4 > 2 = True and that is shown in the output array.

In [95]:
y = np.arange(5)
print(y)
print(y > 2)
print(y.shape)
y[y>2]

[0 1 2 3 4]
[False False False  True  True]
(5,)


array([3, 4])

In [98]:
x = np.random.randint(6,15,15).reshape(3,5)
print(x)
print("##############################################")
#print(x > 9)
print(x.shape)
a = x > 9
print(a)
print("##############################################")
print(a.shape)
print(x[a])
print(x.shape)

[[ 9 14  6 14  9]
 [11 13 12 13 10]
 [13 13 11  7 13]]
##############################################
(3, 5)
[[False  True False  True False]
 [ True  True  True  True  True]
 [ True  True  True False  True]]
##############################################
(3, 5)
[14 14 11 13 12 13 10 13 13 11 13]
(3, 5)


In [99]:
indices = np.random.permutation(arrayLength)
print(indices)
print(indices >= 3)
print(indices[indices >=3])

[0 1 4 3 2]
[False False  True  True False]
[4 3]


#### Use boolean values to index arrays

Once we have created our boolean array we can use it to index other arrays.

The rule is very simple. If at position i of index we have True include `x[i]` in the output.

In [100]:
indices = np.random.permutation(arrayLength)
print(indices)

[0 1 2 3 4]


In [ ]:
print(x > 2)
print("#######################################")
print(x[x > 9])
print("#######################################")
print(x)
print(x[np.array([False,True,False,True,False])])

## Array Math

#### Try adding to a list

In [101]:
x = [1, 2, 3, 4]
#print(x*10)

print(x + 10)

TypeError: can only concatenate list (not "int") to list

#### Try again with an array

When trying with a list you got an error because simple python lists do not support addition with scalars.

But numpy arrays do allow that.

In [102]:
x = np.array([1,2,3,4]).reshape(2,2)
print(x)
print("#######################")
print(x + 10)
print("#######################")
print(x * 10)

[[1 2]
 [3 4]]
#######################
[[11 12]
 [13 14]]
#######################
[[10 20]
 [30 40]]


### Finding Transpose -- converting rows and columns to the reverse


In [103]:
a = np.random.randint(0,15,15).reshape(3,5)
print(a)
print("################## - Transpose")
b = a.transpose()
print(b)

[[11  3  5  0  6]
 [ 3  5 11 10 12]
 [ 0 14  8  8  5]]
################## - Transpose
[[11  3  0]
 [ 3  5 14]
 [ 5 11  8]
 [ 0 10  8]
 [ 6 12  5]]


In [104]:
a = np.random.randint(0,15,30).reshape(3,5,2)
print(a)
print("################## - Transpose")
b = a.transpose()
print(b)

[[[ 0  0]
  [12 10]
  [13  7]
  [ 1 11]
  [13 13]]

 [[ 9  7]
  [13  8]
  [12 13]
  [12  4]
  [ 6  3]]

 [[13  1]
  [ 1  7]
  [ 4 10]
  [ 6  1]
  [12  6]]]
################## - Transpose
[[[ 0  9 13]
  [12 13  1]
  [13 12  4]
  [ 1 12  6]
  [13  6 12]]

 [[ 0  7  1]
  [10  8  7]
  [ 7 13 10]
  [11  4  1]
  [13  3  6]]]


In [105]:
a = np.arange(0,16).reshape(2,2,4)
print(a)
print("################## - Transpose")
b = a.transpose()
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
################## - Transpose
[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [108]:
u = np.eye(10)
#u = np.eye(4,2)
#u = np.eye(2)
print(u)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


    ##### Reading Data From Diskf

In [111]:
from io import StringIO
data = "1, 2, 3\n 4, 5, 6"
data_1 = """1, 2, 3
4, 5, 6"""
array = np.genfromtxt(StringIO(data), delimiter=",")
print(array)
print("########################")
array1 = np.genfromtxt(StringIO(data_1), delimiter=",")
print(array1)

[[1. 2. 3.]
 [4. 5. 6.]]
########################
[[1. 2. 3.]
 [4. 5. 6.]]


In [112]:
data = "  1112  3\n  4 5 67\n890123 4"
array = np.genfromtxt(StringIO(data), delimiter=3)
print(array)
print(array.dtype)

[[  1. 112.   3.]
 [  4.   5.  67.]
 [890. 123.   4.]]
float64


In [ ]:
#### Auto Stripping Values

In [114]:
data = "1, abc , 2\n 3, xxx, 4"
arr = np.genfromtxt(StringIO(data), delimiter=",", dtype="|S5")
print(arr)
print(arr.dtype)

[[b'1' b' abc ' b' 2']
 [b'3' b' xxx' b' 4']]
|S5


Comments

In [118]:
data = """#
 # Skip me !
 # Skip me too !
 1,2
 1, 2
 3, 4
 5, 6 #6 #This is the third line of the data
 7, 8
 # And here comes the last line
 9, 0
 """
print(np.genfromtxt(StringIO(data), comments="#", delimiter=","))


[[1. 2.]
 [1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]
 [9. 0.]]


In [119]:
data_1 = """#,
 $ Skip, me !
 1,2
 1, 2
 3, 4
 # Skip ,me too !
 5, 6 #This is the third line of the data
 7, 8
 # And here comes, the last line
 9, 0
 """
print("####################################")
print(np.genfromtxt(StringIO(data_1), comments ="$", delimiter=",", skip_header=3, skip_footer=3))
print("####################################")
print(np.genfromtxt(StringIO(data_1), comments ="#", delimiter=",", skip_header=3, skip_footer=3))



####################################
[[ 1.  2.]
 [ 3.  4.]
 [nan nan]
 [ 5. nan]]
####################################
[[1. 2.]
 [3. 4.]]


In [120]:
data = "\n".join(str(i) for i in range(10))
print(data)
np.genfromtxt(StringIO(data),comments="#", skip_header=3, skip_footer=5)

0
1
2
3
4
5
6
7
8
9


array([3., 4.])

In [122]:
data = "\n".join("#" + str(i) for i in range(10))
print(data)
np.genfromtxt(StringIO(data), 
comments="#",skip_header=3, skip_footer=5)

#0
#1
#2
#3
#4
#5
#6
#7
#8
#9


c:\python373\lib\site-packages\ipykernel_launcher.py:4: UserWarning: genfromtxt: Empty input file: "<_io.StringIO object at 0x01B1DEE0>"
  after removing the cwd from sys.path.


array([], dtype=float64)

In [125]:
# data = "1 2 3\n4 5 6"
a = np.genfromtxt(StringIO(data))
print(a)
np.genfromtxt(StringIO(data), usecols=(-1,-2))

[[1. 2. 3.]
 [4. 5. 6.]]


array([[3., 2.],
       [6., 5.]])

## Exercises

#### Create an array from 0 to 26 assign it to a variable x

#### Reverse the order of the array and print it out

#### Convert the 1-dimensional array you created into a 3 dimensional array

#### Find the index (location) for value 12

#### Create a random shuffled list of values from 0-19 and assign it to variable y

#### Create an array of boolean values for values in y that are greater than 10

#### Create a random sample of 20 data points from a normal distribution with mean of 10 and standard deviation 5