In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as nm

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)
print (df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [3]:
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
print (df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  


In [4]:
df['is_train']=nm.random.uniform(0,1,len(df)) <=0.75
print (df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True  


In [5]:
train,test = df[df.is_train==True],df[df.is_train==False]

features = df.columns[:4]
print (features)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')


In [6]:
y = pd.factorize(train['species'])[0]

In [13]:
#from sklearn.tree import DecisionTreeClassifier
#clf = DecisionTreeClassifier()

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_jobs=2,random_state=0)

clf.fit(train[features],y)

clf.predict(test[features])

c:\users\john\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\ensemble\forest.py:248: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1,
       2, 1, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [15]:
print (clf.predict_proba(test[features]))

[[1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.1 0.9]
 [0.1 0.9 0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]
 [0.1 0.7 0.2]
 [0.  0.1 0.9]
 [0.  0.5 0.5]
 [0.  0.1 0.9]
 [0.  0.  1. ]
 [0.  0.4 0.6]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]
 [0.  0.  1. ]]


In [16]:
preds = iris.target_names[clf.predict(test[features])]

print (test['species'].head())

10    setosa
12    setosa
23    setosa
26    setosa
27    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]


In [17]:
print (pd.crosstab(test['species'],preds,rownames=['Actual Species'],colnames=['Predicted Species']))

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 10           0          0
versicolor              0           9          1
virginica               0           2          9


In [18]:
preds = iris.target_names[clf.predict([[5.0,3.6,1.4,2]])]

In [19]:
print(preds)

['versicolor']
